from abc import ABC, abstractmethod


class BaseEmbeddingService(ABC):
    """Any embedding backend (local, OpenAI, etc.) implements this interface."""

    @abstractmethod
    def embed(self, text: str) -> list[float]:
        """Transform a text into a numeric vector."""
        raise NotImplementedError

    @abstractmethod
    def embed_batch(self, texts: list[str]) -> list[list[float]]:
        """Transform multiple texts at once for more efficient batch processing."""
        raise NotImplementedError

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Return the dimensionality of vectors generated by this model."""
        raise NotImplementedError
